In [53]:
import time
import numpy as np

In [29]:
from bs4 import BeautifulSoup as bs
import requests

titles_list =[]
date_times_list =[]
for page in range(1,157):
    time.sleep(2)
    url = 'https://www.paxnet.co.kr/stock/report/report?menuCode=1111&currentPageNo='+str(page)+'&reportId=0&searchKey=title&searchValue='

    response = requests.get(url)
    html_text=response.text

    soup = bs(html_text, 'html.parser')

    titles = soup.select('div.board-type > ul > li > div:nth-child(2) > p > a')
    date_times = soup.select('div.board-type > ul > li > div:nth-child(5)')

    for i in titles:
        title = i.get_text()
        titles_list.append(title)
        #print(title)

    for i in date_times:
        date_time = i.get_text()
        new_date_time = date_time.replace('.', '-')
        if new_date_time=="작성일":
            continue
        date_times_list.append(new_date_time)
        #print(new_date_time)
df=pd.DataFrame()
df["titles"]=titles_list
df["date"]=date_times_list
df

                                          titles        date
0                                 선물옵션시장 지표_1202  2022-12-12
1                    [주식시장 투자전략] 긍정적인 부분을 확인한 연말  2022-12-12
2                        [주식시장 투자전략] 연말 펀드시장 분위기  2022-12-12
3     [KIWOOM Daily] 미 증시, 저가매수세 유입되며 6 거래일만에 반등  2022-12-09
4                                 선물옵션시장 지표_1209  2022-12-09
...                                          ...         ...
4656                               잠재 리스크 요인의 부각  2016-01-07
4657                        기관 반발 매수세에 힘입은 상승 마감  2016-01-06
4658                                中 증시, 안정 찾나?  2016-01-06
4659                      중국 증시 폭락에 영향, 4달 만에 최저  2016-01-05
4660                              중국, 제조업 부진에 하락  2016-01-04

[4661 rows x 2 columns]

In [34]:
df.to_csv("크롤링데이터.csv",encoding='cp949',index=False)

In [31]:
cospy=pd.read_csv("코스피변동.csv")

In [46]:
cospy

      Unnamed: 0        Date        KOSPI  Price
0              0  2012-01-02  1826.369995      1
1              1  2012-01-03  1875.410034      0
2              2  2012-01-04  1866.219971      0
3              3  2012-01-05  1863.739990      0
4              4  2012-01-06  1843.140015      0
...          ...         ...          ...    ...
2686        2686  2022-12-02  2434.330078      0
2687        2687  2022-12-05  2419.320068      0
2688        2688  2022-12-06  2393.159912      0
2689        2689  2022-12-07  2382.810059      0
2690        2690  2022-12-08  2364.330078      0

[2691 rows x 4 columns]

In [40]:
cospydic={}

In [41]:
for x,y in zip(cospy["Date"],cospy["Price"]):
    cospydic[x]=y

In [44]:
cospydic

{'2012-01-02': 1,
 '2012-01-03': 0,
 '2012-01-04': 0,
 '2012-01-05': 0,
 '2012-01-06': 0,
 '2012-01-09': 1,
 '2012-01-10': 0,
 '2012-01-11': 1,
 '2012-01-12': 1,
 '2012-01-13': 0,
 '2012-01-16': 1,
 '2012-01-17': 0,
 '2012-01-18': 1,
 '2012-01-19': 1,
 '2012-01-20': 1,
 '2012-01-25': 1,
 '2012-01-26': 1,
 '2012-01-27': 0,
 '2012-01-30': 1,
 '2012-01-31': 1,
 '2012-02-01': 1,
 '2012-02-02': 0,
 '2012-02-03': 1,
 '2012-02-06': 1,
 '2012-02-07': 1,
 '2012-02-08': 1,
 '2012-02-09': 0,
 '2012-02-10': 1,
 '2012-02-13': 0,
 '2012-02-14': 1,
 '2012-02-15': 0,
 '2012-02-16': 1,
 '2012-02-17': 1,
 '2012-02-20': 0,
 '2012-02-21': 1,
 '2012-02-22': 0,
 '2012-02-23': 1,
 '2012-02-24': 0,
 '2012-02-27': 1,
 '2012-02-28': 1,
 '2012-02-29': 1,
 '2012-03-02': 0,
 '2012-03-05': 0,
 '2012-03-06': 0,
 '2012-03-07': 1,
 '2012-03-08': 1,
 '2012-03-09': 0,
 '2012-03-12': 1,
 '2012-03-13': 1,
 '2012-03-14': 0,
 '2012-03-15': 0,
 '2012-03-16': 1,
 '2012-03-19': 0,
 '2012-03-20': 0,
 '2012-03-21': 0,
 '2012-03-22': 1,
 '2012-03-23': 0,
 '2012-03-26': 1,
 '2012-03-27': 0,
 '2012-03-28': 0,
 '2012-03-29': 0,
 '2012-03-30': 1,
 '2012-04-02': 1,
 '2012-04-03': 0,
 '2012-04-04': 1,
 '2012-04-05': 1,
 '2012-04-06': 0,
 '2012-04-09': 0,
 '2012-04-10': 0,
 '2012-04-12': 1,
 '2012-04-13': 0,
 '2012-04-16': 0,
 '2012-04-17': 1,
 '2012-04-18': 0,
 '2012-04-19': 0,
 '2012-04-20': 0,
 '2012-04-23': 0,
 '2012-04-24': 0,
 '2012-04-25': 1,
 '2012-04-26': 1,
 '2012-04-27': 1,
 '2012-04-30': 1,
 '2012-05-02': 0,
 '2012-05-03': 0,
 '2012-05-04': 0,
 '2012-05-07': 1,
 '2012-05-08': 0,
 '2012-05-09': 0,
 '2012-05-10': 0,
 '2012-05-11': 0,
 '2012-05-14': 0,
 '2012-05-15': 0,
 '2012-05-16': 1,
 '2012-05-17': 0,
 '2012-05-18': 1,
 '2012-05-21': 1,
 '2012-05-22': 0,
 '2012-05-23': 1,
 '2012-05-24': 1,
 '2012-05-25': 1,
 '2012-05-29': 0,
 '2012-05-30': 0,
 '2012-05-31': 0,
 '2012-06-01': 0,
 '2012-06-04': 1,
 '2012-06-05': 1,
 '2012-06-07': 0,
 '2012-06-08': 1,
 '2012-06-11': 0,
 '2012-06-12': 1,
 '2012-06-13': 1,
 '2012-06-14': 0,
 '2012-06-15': 1,
 '2012-06-18': 1,
 '2012-06-19': 1,
 '2012-06-20': 0,
 '2012-06-21': 0,
 '2012-06-22': 0,
 '2012-06-25': 0,
 '2012-06-26': 0,
 '2012-06-27': 1,
 '2012-06-28': 1,
 '2012-06-29': 0,
 '2012-07-02': 1,
 '2012-07-03': 1,
 '2012-07-04': 1,
 '2012-07-05': 0,
 '2012-07-06': 0,
 '2012-07-09': 0,
 '2012-07-10': 0,
 '2012-07-11': 0,
 '2012-07-12': 1,
 '2012-07-13': 1,
 '2012-07-16': 1,
 '2012-07-17': 0,
 '2012-07-18': 1,
 '2012-07-19': 0,
 '2012-07-20': 0,
 '2012-07-23': 1,
 '2012-07-24': 0,
 '2012-07-25': 1,
 '2012-07-26': 1,
 '2012-07-27': 1,
 '2012-07-30': 1,
 '2012-07-31': 0,
 '2012-08-01': 0,
 '2012-08-02': 0,
 '2012-08-03': 1,
 '2012-08-06': 1,
 '2012-08-07': 1,
 '2012-08-08': 1,
 '2012-08-09': 1,
 '2012-08-10': 0,
 '2012-08-13': 1,
 '2012-08-14': 1,
 '2012-08-16': 0,
 '2012-08-17': 0,
 '2012-08-20': 0,
 '2012-08-21': 0,
 '2012-08-22': 1,
 '2012-08-23': 0,
 '2012-08-24': 0,
 '2012-08-27': 0,
 '2012-08-28': 1,
 '2012-08-29': 0,
 '2012-08-30': 0,
 '2012-08-31': 1,
 '2012-09-03': 0,
 '2012-09-04': 0,
 '2012-09-05': 1,
 '2012-09-06': 1,
 '2012-09-07': 0,
 '2012-09-10': 0,
 '2012-09-11': 1,
 '2012-09-12': 1,
 '2012-09-13': 1,
 '2012-09-14': 0,
 '2012-09-17': 1,
 '2012-09-18': 1,
 '2012-09-19': 0,
 '2012-09-20': 1,
 '2012-09-21': 1,
 '2012-09-24': 0,
 '2012-09-25': 0,
 '2012-09-26': 1,
 '2012-09-27': 1,
 '2012-09-28': 0,
 '2012-10-02': 0,
 '2012-10-04': 1,
 '2012-10-05': 0,
 '2012-10-08': 0,
 '2012-10-09': 0,
 '2012-10-10': 0,
 '2012-10-11': 1,
 '2012-10-12': 0,
 '2012-10-15': 1,
 '2012-10-16': 1,
 '2012-10-17': 1,
 '2012-10-18': 0,
 '2012-10-19': 0,
 '2012-10-22': 0,
 '2012-10-23': 0,
 '2012-10-24': 1,
 '2012-10-25': 0,
 '2012-10-26': 1,
 '2012-10-29': 1,
 '2012-10-30': 1,
 '2012-10-31': 0,
 '2012-11-01': 1,
 '2012-11-02': 0,
 '2012-11-05': 1,
 '2012-11-06': 1,
 '2012-11-07': 0,
 '2012-11-08': 0,
 '2012-11-09': 0,
 '2012-11-12': 0,
 '2012-11-13': 1,
 '2012-11-14': 0,
 '2012-11-15': 0,
 '2012-11-16': 1,
 '2012-11-19': 1,
 '2012-11-20': 0,
 '2012-11-21': 1,
 '2012-11-22': 1,
 '2012-11-23': 0,
 '2012-11-26': 1,
 '2012-11-27': 0,
 '2012-11-28': 1,
 '2012-11-29': 0,
 '2012-11-30': 1,
 '2012-12-03': 0,
 '2012-12-04': 1,
 '2012-12-05': 1,
 '2012-12-06': 1,
 '2012-12-07': 0,
 '2012-12-10': 1,
 '2012-12-11': 1,
 '2012-12-12': 1,
 '2012-12-13': 0,
 '2012-12-14': 0,
 '2012-12-17': 1,
 '2012-12-18': 1,
 '2012-12-20': 0,
 '2012-12-21': 1,
 '2012-12-24': 1,
 '2012-12-26': 1,
 '2012-12-27': 1,
 '2012-12-28': 1,
 '2013-01-02': 0,
 '2013-01-03': 0,
 '2013-01-04': 0,
 '2013-01-07': 0,
 '2013-01-08': 0,
 '2013-01-09': 1,
 '2013-01-10': 0,
 '2013-01-11': 1,
 '2013-01-14': 0,
 '2013-01-15': 0,
 '2013-01-16': 0,
 '2013-01-17': 1,
 '2013-01-18': 0,
 '2013-01-21': 1,
 '2013-01-22': 0,
 '2013-01-23': 0,
 '2013-01-24': 0,
 '2013-01-25': 0,
 '2013-01-28': 1,
 '2013-01-29': 1,
 '2013-01-30': 0,
 '2013-01-31': 0,
 '2013-02-01': 0,
 '2013-02-04': 0,
 '2013-02-05': 0,
 '2013-02-06': 0,
 '2013-02-07': 1,
 '2013-02-08': 0,
 '2013-02-12': 1,
 '2013-02-13': 1,
 '2013-02-14': 1,
 '2013-02-15': 1,
 '2013-02-18': 1,
 '2013-02-19': 1,
 '2013-02-20': 0,
 '2013-02-21': 1,
 '2013-02-22': 0,
 '2013-02-25': 0,
 '2013-02-26': 1,
 '2013-02-27': 1,
 '2013-02-28': 0,
 '2013-03-04': 1,
 '2013-03-05': 1,
 '2013-03-06': 0,
 '2013-03-07': 1,
 '2013-03-08': 0,
 '2013-03-11': 0,
 '2013-03-12': 1,
 '2013-03-13': 1,
 '2013-03-14': 0,
 '2013-03-15': 0,
 '2013-03-18': 1,
 '2013-03-19': 0,
 '2013-03-20': 0,
 '2013-03-21': 0,
 '2013-03-22': 1,
 '2013-03-25': 1,
 '2013-03-26': 1,
 '2013-03-27': 1,
 '2013-03-28': 1,
 '2013-03-29': 0,
 '2013-04-01': 0,
 '2013-04-02': 0,
 '2013-04-03': 0,
 '2013-04-04': 0,
 '2013-04-05': 0,
 '2013-04-08': 1,
 '2013-04-09': 1,
 '2013-04-10': 1,
 '2013-04-11': 0,
 '2013-04-12': 0,
 '2013-04-15': 1,
 '2013-04-16': 1,
 '2013-04-17': 0,
 '2013-04-18': 1,
 '2013-04-19': 1,
 '2013-04-22': 0,
 '2013-04-23': 1,
 '2013-04-24': 1,
 '2013-04-25': 0,
 '2013-04-26': 0,
 '2013-04-29': 1,
 '2013-04-30': 0,
 '2013-05-02': 1,
 '2013-05-03': 0,
 '2013-05-06': 0,
 '2013-05-07': 1,
 '2013-05-08': 1,
 '2013-05-09': 0,
 '2013-05-10': 1,
 '2013-05-13': 1,
 '2013-05-14': 1,
 '2013-05-15': 1,
 '2013-05-16': 0,
 '2013-05-20': 0,
 '2013-05-21': 1,
 '2013-05-22': 0,
 '2013-05-23': 1,
 '2013-05-24': 1,
 '2013-05-27': 1,
 '2013-05-28': 1,
 '2013-05-29': 0,
 '2013-05-30': 1,
 '2013-05-31': 0,
 '2013-06-03': 0,
 '2013-06-04': 0,
 '2013-06-05': 0,
 '2013-06-07': 1,
 '2013-06-10': 0,
 '2013-06-11': 0,
 '2013-06-12': 0,
 '2013-06-13': 1,
 '2013-06-14': 0,
 '2013-06-17': 1,
 '2013-06-18': 0,
 '2013-06-19': 0,
 '2013-06-20': 0,
 '2013-06-21': 0,
 '2013-06-24': 0,
 '2013-06-25': 1,
 '2013-06-26': 1,
 '2013-06-27': 1,
 '2013-06-28': 0,
 '2013-07-01': 0,
 '2013-07-02': 0,
 '2013-07-03': 1,
 '2013-07-04': 0,
 '2013-07-05': 0,
 '2013-07-08': 1,
 '2013-07-09': 0,
 '2013-07-10': 1,
 '2013-07-11': 0,
 '2013-07-12': 1,
 '2013-07-15': 0,
 '2013-07-16': 1,
 '2013-07-17': 0,
 '2013-07-18': 0,
 '2013-07-19': 1,
 '2013-07-22': 1,
 '2013-07-23': 1,
 '2013-07-24': 0,
 '2013-07-25': 1,
 '2013-07-26': 0,
 '2013-07-29': 1,
 '2013-07-30': 0,
 '2013-07-31': 1,
 '2013-08-01': 1,
 '2013-08-02': 0,
 '2013-08-05': 0,
 '2013-08-06': 0,
 '2013-08-07': 1,
 '2013-08-08': 0,
 '2013-08-09': 1,
 '2013-08-12': 1,
 '2013-08-13': 1,
 '2013-08-14': 0,
 '2013-08-16': 0,
 '2013-08-19': 0,
 '2013-08-20': 0,
 '2013-08-21': 0,
 '2013-08-22': 1,
 '2013-08-23': 1,
 '2013-08-26': 0,
 '2013-08-27': 0,
 '2013-08-28': 1,
 '2013-08-29': 1,
 '2013-08-30': 0,
 '2013-09-02': 1,
 '2013-09-03': 0,
 '2013-09-04': 1,
 '2013-09-05': 1,
 '2013-09-06': 1,
 '2013-09-09': 1,
 '2013-09-10': 1,
 '2013-09-11': 1,
 '2013-09-12': 0,
 '2013-09-13': 1,
 '2013-09-16': 0,
 '2013-09-17': 1,
 '2013-09-23': 0,
 '2013-09-24': 0,
 '2013-09-25': 1,
 '2013-09-26': 1,
 '2013-09-27': 0,
 '2013-09-30': 1,
 '2013-10-01': 1,
 '2013-10-02': 0,
 '2013-10-04': 0,
 '2013-10-07': 1,
 '2013-10-08': 0,
 '2013-10-10': 1,
 '2013-10-11': 0,
 '2013-10-14': 1,
 '2013-10-15': 0,
 '2013-10-16': 1,
 '2013-10-17': 1,
 '2013-10-18': 1,
 '2013-10-21': 1,
 '2013-10-22': 0,
 '2013-10-23': 1,
 '2013-10-24': 0,
 '2013-10-25': 1,
 '2013-10-28': 1,
 '2013-10-29': 1,
 '2013-10-30': 0,
 '2013-10-31': 1,
 '2013-11-01': 0,
 '2013-11-04': 0,
 '2013-11-05': 0,
 '2013-11-06': 0,
 '2013-11-07': 0,
 '2013-11-08': 0,
 '2013-11-11': 1,
 '2013-11-12': 0,
 '2013-11-13': 1,
 '2013-11-14': 1,
 '2013-11-15': 1,
 '2013-11-18': 1,
 '2013-11-19': 0,
 '2013-11-20': 0,
 '2013-11-21': 1,
 '2013-11-22': 1,
 '2013-11-25': 1,
 '2013-11-26': 1,
 '2013-11-27': 1,
 '2013-11-28': 0,
 '2013-11-29': 0,
 '2013-12-02': 0,
 '2013-12-03': 0,
 '2013-12-04': 0,
 '2013-12-05': 0,
 '2013-12-06': 1,
 '2013-12-09': 0,
 '2013-12-10': 0,
 '2013-12-11': 0,
 '2013-12-12': 0,
 '2013-12-13': 0,
 '2013-12-16': 1,
 '2013-12-17': 1,
 '2013-12-18': 1,
 '2013-12-19': 1,
 '2013-12-20': 1,
 '2013-12-23': 1,
 '2013-12-24': 0,
 '2013-12-26': 1,
 '2013-12-27': 1,
 '2013-12-30': 0,
 '2014-01-02': 0,
 '2014-01-03': 1,
 '2014-01-06': 1,
 '2014-01-07': 0,
 '2014-01-08': 0,
 '2014-01-09': 0,
 '2014-01-10': 1,
 '2014-01-13': 0,
 '2014-01-14': 1,
 '2014-01-15': 1,
 '2014-01-16': 0,
 '2014-01-17': 1,
 '2014-01-20': 1,
 '2014-01-21': 1,
 '2014-01-22': 0,
 '2014-01-23': 0,
 '2014-01-24': 0,
 '2014-01-27': 1,
 '2014-01-28': 1,
 '2014-01-29': 0,
 '2014-02-03': 0,
 '2014-02-04': 1,
 '2014-02-05': 1,
 '2014-02-06': 1,
 '2014-02-07': 1,
 '2014-02-10': 1,
 '2014-02-11': 1,
 '2014-02-12': 0,
 '2014-02-13': 1,
 '2014-02-14': 1,
 '2014-02-17': 1,
 '2014-02-18': 0,
 '2014-02-19': 0,
 '2014-02-20': 1,
 '2014-02-21': 0,
 '2014-02-24': 1,
 '2014-02-25': 1,
 '2014-02-26': 1,
 '2014-02-27': 1,
 '2014-02-28': 0,
 '2014-03-03': 0,
 '2014-03-04': 1,
 '2014-03-05': 1,
 '2014-03-06': 0,
 '2014-03-07': 0,
 '2014-03-10': 1,
 '2014-03-11': 0,
 '2014-03-12': 1,
 '2014-03-13': 0,
 '2014-03-14': 1,
 '2014-03-17': 1,
 '2014-03-18': 0,
 '2014-03-19': 0,
 '2014-03-20': 1,
 '2014-03-21': 1,
 '2014-03-24': 0,
 '2014-03-25': 1,
 '2014-03-26': 1,
 '2014-03-27': 1,
 '2014-03-28': 1,
 '2014-03-31': 1,
 '2014-04-01': 1,
 '2014-04-02': 0,
 '2014-04-03': 0,
 '2014-04-04': 1,
 '2014-04-07': 1,
 '2014-04-08': 1,
 '2014-04-09': 1,
 '2014-04-10': 0,
 '2014-04-11': 0,
 '2014-04-14': 0,
 '2014-04-15': 0,
 '2014-04-16': 0,
 '2014-04-17': 1,
 '2014-04-18': 0,
 '2014-04-21': 1,
 '2014-04-22': 0,
 '2014-04-23': 0,
 '2014-04-24': 0,
 '2014-04-25': 0,
 '2014-04-28': 0,
 '2014-04-29': 0,
 '2014-04-30': 0,
 '2014-05-02': 0,
 '2014-05-07': 1,
 '2014-05-08': 1,
 '2014-05-09': 1,
 '2014-05-12': 1,
 '2014-05-13': 1,
 '2014-05-14': 0,
 '2014-05-15': 1,
 '2014-05-16': 1,
 '2014-05-19': 0,
 '2014-05-20': 0,
 '2014-05-21': 1,
 '2014-05-22': 1,
 '2014-05-23': 0,
 '2014-05-26': 0,
 '2014-05-27': 1,
 '2014-05-28': 0,
 '2014-05-29': 0,
 '2014-05-30': 1,
 '2014-06-02': 1,
 '2014-06-03': 0,
 '2014-06-05': 0,
 '2014-06-09': 1,
 '2014-06-10': 1,
 '2014-06-11': 0,
 '2014-06-12': 0,
 '2014-06-13': 1,
 '2014-06-16': 1,
 '2014-06-17': 0,
 '2014-06-18': 1,
 '2014-06-19': 0,
 '2014-06-20': 1,
 '2014-06-23': 1,
 '2014-06-24': 0,
 '2014-06-25': 1,
 '2014-06-26': 0,
 '2014-06-27': 1,
 '2014-06-30': 0,
 '2014-07-01': 1,
 '2014-07-02': 0,
 '2014-07-03': 0,
 '2014-07-04': 0,
 '2014-07-07': 1,
 '2014-07-08': 0,
 '2014-07-09': 1,
 '2014-07-10': 0,
 '2014-07-11': 1,
 '2014-07-14': 1,
 '2014-07-15': 1,
 '2014-07-16': 1,
 '2014-07-17': 0,
 '2014-07-18': 0,
 '2014-07-21': 1,
 '2014-07-22': 0,
 '2014-07-23': 0,
 '2014-07-24': 1,
 '2014-07-25': 1,
 '2014-07-28': 1,
 '2014-07-29': 1,
 '2014-07-30': 0,
 '2014-07-31': 0,
 '2014-08-01': 1,
 '2014-08-04': 0,
 '2014-08-05': 0,
 '2014-08-06': 0,
 '2014-08-07': 0,
 '2014-08-08': 1,
 '2014-08-11': 1,
 '2014-08-12': 1,
 '2014-08-13': 1,
 '2014-08-14': 0,
 '2014-08-18': 1,
 '2014-08-19': 1,
 '2014-08-20': 0,
 '2014-08-21': 1,
 '2014-08-22': 1,
 '2014-08-25': 1,
 '2014-08-26': 1,
 '2014-08-27': 1,
 '2014-08-28': 0,
 '2014-08-29': 0,
 '2014-09-01': 0,
 '2014-09-02': 0,
 '2014-09-03': 1,
 '2014-09-04': 0,
 '2014-09-05': 0,
 '2014-09-11': 1,
 '2014-09-12': 0,
 '2014-09-15': 1,
 '2014-09-16': 1,
 '2014-09-17': 0,
 '2014-09-18': 1,
 '2014-09-19': 0,
 '2014-09-22': 0,
 '2014-09-23': 1,
 '2014-09-24': 0,
 '2014-09-25': 0,
 '2014-09-26': 0,
 '2014-09-29': 0,
 '2014-09-30': 0,
 '2014-10-01': 0,
 '2014-10-02': 0,
 '2014-10-06': 1,
 '2014-10-07': 0,
 '2014-10-08': 0,
 '2014-10-10': 0,
 '2014-10-13': 1,
 '2014-10-14': 0,
 '2014-10-15': 0,
 '2014-10-16': 0,
 '2014-10-17': 1,
 '2014-10-20': 0,
 '2014-10-21': 1,
 '2014-10-22': 0,
 '2014-10-23': 0,
 '2014-10-24': 1,
 '2014-10-27': 0,
 '2014-10-28': 1,
 '2014-10-29': 0,
 '2014-10-30': 1,
 '2014-10-31': 0,
 '2014-11-03': 0,
 '2014-11-04': 0,
 '2014-11-05': 1,
 '2014-11-06': 1,
 '2014-11-07': 1,
 '2014-11-10': 1,
 '2014-11-11': 1,
 '2014-11-12': 0,
 '2014-11-13': 0,
 '2014-11-14': 0,
 '2014-11-17': 1,
 '2014-11-18': 0,
 '2014-11-19': 0,
 '2014-11-20': 1,
 '2014-11-21': 1,
 '2014-11-24': 1,
 '2014-11-25': 1,
 '2014-11-26': 1,
 '2014-11-27': 0,
 '2014-11-28': 0,
 '2014-12-01': 1,
 '2014-12-02': 1,
 '2014-12-03': 1,
 '2014-12-04': 1,
 '2014-12-05': 0,
 '2014-12-08': 0,
 '2014-12-09': 0,
 '2014-12-10': 0,
 '2014-12-11': 1,
 '2014-12-12': 0,
 '2014-12-15': 0,
 '2014-12-16': 0,
 '2014-12-17': 0,
 '2014-12-18': 1,
 '2014-12-19': 1,
 '2014-12-22': 0,
 '2014-12-23': 1,
 '2014-12-24': 1,
 '2014-12-26': 0,
 '2014-12-29': 0,
 '2014-12-30': 1,
 '2015-01-02': 0,
 '2015-01-05': 0,
 '2015-01-06': 1,
 '2015-01-07': 1,
 '2015-01-08': 1,
 '2015-01-09': 0,
 '2015-01-12': 0,
 '2015-01-13': 0,
 '2015-01-14': 1,
 '2015-01-15': 0,
 '2015-01-16': 1,
 '2015-01-19': 1,
 '2015-01-20': 1,
 '2015-01-21': 0,
 '2015-01-22': 1,
 '2015-01-23': 0,
 '2015-01-26': 1,
 '2015-01-27': 1,
 '2015-01-28': 0,
 '2015-01-29': 0,
 '2015-01-30': 1,
 '2015-02-02': 0,
 '2015-02-03': 1,
 '2015-02-04': 0,
 '2015-02-05': 1,
 '2015-02-06': 0,
 '2015-02-09': 0,
 '2015-02-10': 1,
 '2015-02-11': 0,
 '2015-02-12': 1,
 '2015-02-13': 1,
 '2015-02-16': 1,
 '2015-02-17': 1,
 '2015-02-23': 1,
 '2015-02-24': 1,
 '2015-02-25': 1,
 '2015-02-26': 0,
 '2015-02-27': 1,
 '2015-03-02': 1,
 '2015-03-03': 0,
 '2015-03-04': 1,
 '2015-03-05': 1,
 '2015-03-06': 0,
 '2015-03-09': 0,
 '2015-03-10': 0,
 '2015-03-11': 0,
 '2015-03-12': 1,
 '2015-03-13': 1,
 '2015-03-16': 1,
 '2015-03-17': 0,
 '2015-03-18': 1,
 '2015-03-19': 0,
 '2015-03-20': 0,
 '2015-03-23': 1,
 '2015-03-24': 1,
 '2015-03-25': 0,
 '2015-03-26': 0,
 '2015-03-27': 1,
 '2015-03-30': 1,
 '2015-03-31': 0,
 '2015-04-01': 1,
 '2015-04-02': 1,
 '2015-04-03': 1,
 '2015-04-06': 1,
 '2015-04-07': 1,
 '2015-04-08': 0,
 '2015-04-09': 1,
 '2015-04-10': 1,
 '2015-04-13': 1,
 '2015-04-14': 1,
 '2015-04-15': 1,
 '2015-04-16': 1,
 '2015-04-17': 1,
 '2015-04-20': 0,
 '2015-04-21': 0,
 '2015-04-22': 1,
 '2015-04-23': 0,
 '2015-04-24': 0,
 '2015-04-27': 0,
 '2015-04-28': 0,
 '2015-04-29': 0,
 '2015-04-30': 1,
 '2015-05-04': 0,
 '2015-05-06': 0,
 '2015-05-07': 0,
 '2015-05-08': 1,
 '2015-05-11': 0,
 '2015-05-12': 1,
 '2015-05-13': 1,
 '2015-05-14': 0,
 '2015-05-15': 1,
 '2015-05-18': 1,
 '2015-05-19': 1,
 '2015-05-20': 0,
 '2015-05-21': 1,
 '2015-05-22': 0,
 '2015-05-26': 0,
 '2015-05-27': 1,
 '2015-05-28': 1,
 '2015-05-29': 0,
 '2015-06-01': 0,
 '2015-06-02': 0,
 '2015-06-03': 1,
 '2015-06-04': 0,
 '2015-06-05': 0,
 '2015-06-08': 0,
 '2015-06-09': 0,
 '2015-06-10': 1,
 '2015-06-11': 0,
 '2015-06-12': 0,
 '2015-06-15': 0,
 '2015-06-16': 1,
 '2015-06-17': 1,
 '2015-06-18': 1,
 '2015-06-19': 1,
 '2015-06-22': 1,
 '2015-06-23': 1,
 '2015-06-24': 0,
 '2015-06-25': 1,
 '2015-06-26': 0,
 '2015-06-29': 1,
 '2015-06-30': 1,
 '2015-07-01': 1,
 '2015-07-02': 0,
 '2015-07-03': 0,
 '2015-07-06': 0,
 '2015-07-07': 0,
 '2015-07-08': 1,
 '2015-07-09': 1,
 '2015-07-10': 1,
 '2015-07-13': 0,
 '2015-07-14': 1,
 '2015-07-15': 1,
 '2015-07-16': 0,
 '2015-07-17': 0,
 '2015-07-20': 1,
 '2015-07-21': 0,
 '2015-07-22': 1,
 '2015-07-23': 0,
 '2015-07-24': 0,
 '2015-07-27': 1,
 '2015-07-28': 0,
 '2015-07-29': 0,
 '2015-07-30': 1,
 '2015-07-31': 0,
 '2015-08-03': 1,
 '2015-08-04': 1,
 '2015-08-05': 0,
 '2015-08-06': 0,
 '2015-08-07': 0,
 '2015-08-10': 0,
 '2015-08-11': 0,
 '2015-08-12': 1,
 '2015-08-13': 0,
 '2015-08-14': 0,
 '2015-08-17': 0,
 '2015-08-18': 0,
 '2015-08-19': 0,
 '2015-08-20': 0,
 '2015-08-21': 0,
 '2015-08-24': 1,
 '2015-08-25': 1,
 '2015-08-26': 1,
 '2015-08-27': 1,
 '2015-08-28': 1,
 '2015-08-31': 0,
 '2015-09-01': 1,
 '2015-09-02': 1,
 '2015-09-03': 0,
 '2015-09-04': 0,
 '2015-09-07': 0,
 '2015-09-08': 1,
 '2015-09-09': 1,
 '2015-09-10': 0,
 '2015-09-11': 0,
 '2015-09-14': 1,
 '2015-09-15': 1,
 '2015-09-16': 1,
 '2015-09-17': 1,
 '2015-09-18': 0,
 '2015-09-21': 1,
 '2015-09-22': 0,
 '2015-09-23': 1,
 '2015-09-24': 0,
 '2015-09-25': 1,
 '2015-09-30': 1,
 '2015-10-01': 0,
 '2015-10-02': 1,
 '2015-10-05': 1,
 '2015-10-06': 1,
 '2015-10-07': 1,
 '2015-10-08': 1,
 '2015-10-12': 0,
 '2015-10-13': 0,
 '2015-10-14': 1,
 '2015-10-15': 0,
 '2015-10-16': 1,
 '2015-10-19': 1,
 '2015-10-20': 1,
 '2015-10-21': 0,
 '2015-10-22': 1,
 '2015-10-23': 1,
 '2015-10-26': 0,
 '2015-10-27': 0,
 '2015-10-28': 0,
 '2015-10-29': 0,
 '2015-10-30': 1,
 '2015-11-02': 1,
 '2015-11-03': 1,
 '2015-11-04': 0,
 '2015-11-05': 0,
 '2015-11-06': 0,
 '2015-11-09': 0,
 '2015-11-10': 1,
 '2015-11-11': 0,
 '2015-11-12': 0,
 '2015-11-13': 0,
 '2015-11-16': 1,
 '2015-11-17': 0,
 '2015-11-18': 1,
 '2015-11-19': 1,
 '2015-11-20': 1,
 '2015-11-23': 1,
 '2015-11-24': 0,
 '2015-11-25': 1,
 '2015-11-26': 0,
 '2015-11-27': 0,
 '2015-11-30': 1,
 '2015-12-01': 0,
 '2015-12-02': 0,
 '2015-12-03': 0,
 '2015-12-04': 0,
 '2015-12-07': 0,
 '2015-12-08': 0,
 '2015-12-09': 1,
 '2015-12-10': 0,
 '2015-12-11': 0,
 '2015-12-14': 1,
 '2015-12-15': 1,
 '2015-12-16': 1,
 '2015-12-17': 0,
 '2015-12-18': 1,
 '2015-12-21': 1,
 '2015-12-22': 1,
 '2015-12-23': 0,
 '2015-12-24': 0,
 '2015-12-28': 1,
 '2015-12-29': 0,
 '2015-12-30': 0,
 '2016-01-04': 1,
 '2016-01-05': 0,
 '2016-01-06': 0,
 '2016-01-07': 1,
 '2016-01-08': 0,
 '2016-01-11': 0,
 '2016-01-12': 1,
 '2016-01-13': 0,
 '2016-01-14': 0,
 '2016-01-15': 0,
 '2016-01-18': 1,
 ...}

In [51]:
news=df.loc[5:]

In [62]:
news["Price"]=pd.Series(map(lambda x:int(cospydic[x]) if x in cospydic.keys() else np.NaN,news["date"]))

C:\Users\DM\AppData\Local\Temp\ipykernel_25212\52282673.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news["Price"]=pd.Series(map(lambda x:int(cospydic[x]) if x in cospydic.keys() else np.NaN,news["date"]))

In [63]:
news["Price"].value_counts()

1.0    2530
0.0    2107
Name: Price, dtype: int64

In [69]:
news=news.dropna(axis=0)

In [72]:
news.to_csv("크롤링 학습데이터.csv",encoding='cp949',index=False)

In [73]:
news

                                           titles        date  Price
5     [KIWOOM Daily] 미 증시, 소비둔화, 경기 침체 우려로 하락세 지속  2022-12-08    0.0
6              [MORNING CALL] 국내 증시 - 경기침체 우려에 하락  2022-12-08    0.0
7                                  선물옵션시장 지표_1208  2022-12-08    0.0
8     [주식시장 투자전략] 12월 만기, KOSPI200 선물 관련 매물 출회 전망  2022-12-08    0.0
9         [전략공감 2.0] 투자자들과의 Q&A (두 가지 질문을 중심으로..)  2022-12-08    0.0
...                                           ...         ...    ...
4651                                 지속되는 외국인의 이탈  2016-01-12    1.0
4652                               中 반등에도 여전한 불안감  2016-01-11    0.0
4653                              직격탄 맞은 주식, 환율시장  2016-01-08    0.0
4654                              중국의 증시 안정화 조치는?  2016-01-08    0.0
4655                        북 수소탄 실험 소식에도 증시는 무덤덤  2016-01-07    1.0

[4637 rows x 3 columns]

In [77]:
data=pd.read_csv("train.csv",encoding="cp949")

In [78]:
data=data.drop(["Unnamed: 0"],axis=1)

In [84]:
test=data.loc[:503]
train=data.loc[503:]

In [87]:
train.to_csv("train_data.csv",index=False,encoding="cp949")
test.to_csv("test_data.csv",index=False,encoding="cp949")